# Generated by Django 4.1 on 2022-08-15 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education_history',
            name='ref_profile',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='candidate.profile'),
        ),
        migrations.AlterField(
            model_name='work_history',
            name='ref_profile',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='candidate.profile'),
        ),
    ]
