# Generated by Django 4.1 on 2022-08-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_alter_education_history_ref_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
